### ISSUE TITLE
Unable to Add the Author Name while Creating Annotations

### ISSUE THREAD

**Issue by abdulrehman25** [PDFTron/webviewer-typescript-sample#3]
![image](https://user-images.githubusercontent.com/51014352/119573264-71cae600-bdcd-11eb-81ba-6effcbab886b.png)
![image](https://user-images.githubusercontent.com/51014352/119573277-755e6d00-bdcd-11eb-9aed-3abdb08a3121.png)

**Comment by mparizeau-pdftron** [comment]
You can set the Author property of the annotation like this `freeText.Author = 'myAuthorName'`.

Since this isn't specific to the sample repo I'm going to close this issue. But feel free to create a new question in our community forum here if this doesn't answer your question https://community.pdftron.com/
