### ISSUE TITLE
Unable to Disable the Annotation State

### ISSUE THREAD

**Issue by abdulrehman25** [PDFTron/webviewer-typescript-sample#5]
![image](https://user-images.githubusercontent.com/51014352/119573410-a76fcf00-bdcd-11eb-9ff3-95941975756a.png)

**Comment by mparizeau-pdftron** [comment]
Here is how you can hide and show elements in the UI https://www.pdftron.com/documentation/web/guides/hiding-elements/
It looks like the data-element for this is `noteState`. 

Since this isn't specific to the sample repo I'm going to close this issue. But feel free to create a new question in our community forum here https://community.pdftron.com/
